import { createContext, ReactNode, useMemo, useState } from "react";

type Language = "pt" | "en";

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
};

const translations = {
  pt: {
    "a11y.languageToggle": "Alternar idioma do aplicativo",
    "a11y.brandLogo": "Logo BlackTone Music",
    "common.back": "Voltar",
    "common.edit": "Editar",
    "common.loading": "Carregando",
    "common.login": "Login",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.goToLogin": "Ir para login",
    "common.item": "item",
    "common.items": "itens",
    "common.price": "Preço",
    "common.products": "Produtos",
    "common.remove": "Remover",
    "common.save": "Salvar",
    "common.saving": "Salvando...",
    "common.total": "Total",
    "common.tryAgain": "Tente novamente.",
    "common.viewProducts": "Ver produtos",
    "auth.backHint": "Volta para a tela anterior.",
    "auth.emailHint": "Digite seu email no formato exemplo@exemplo.com.",
    "auth.emailPlaceholder": "exemplo@exemplo.com",
    "auth.emailRequired": "Informe seu email.",
    "auth.emailRequiredSignup": "Informe um email.",
    "auth.emailInvalid": "Digite um email no formato exemplo@exemplo.com.",
    "auth.goToSignupHint": "Abre a tela de cadastro.",
    "auth.createAccount": "Criar conta",
    "auth.creatingAccount": "Criando conta...",
    "auth.createAccountHint": "Cria sua conta com email e senha no Firebase.",
    "auth.email": "Email",
    "auth.haveAccount": "Já tenho conta",
    "auth.loginHint": "Entra na conta usando o Firebase Authentication.",
    "auth.loginSubtitle": "Acesse sua conta para concluir compras e acompanhar o histórico.",
    "auth.loginTitle": "Entrar na BlackTone",
    "auth.password": "Senha",
    "auth.passwordHint": "Digite sua senha.",
    "auth.passwordPlaceholder": "Mínimo de 6 caracteres",
    "auth.passwordRequired": "Informe sua senha.",
    "auth.passwordRequiredSignup": "Informe uma senha.",
    "auth.passwordWeak": "Senha precisa ter pelo menos 6 caracteres.",
    "auth.passwordHelper": "Mínimo de 6 caracteres.",
    "auth.emailSignupHint": "Digite seu email para cadastro.",
    "auth.emailSignupLabel": "Email para cadastro",
    "auth.passwordSignupHint": "Digite uma senha com no mínimo 6 caracteres.",
    "auth.passwordSignupLabel": "Senha para cadastro",
    "auth.createAccountAndProfileHint": "Cria sua conta e abre o perfil.",
    "auth.signupPasswordPlaceholder": "Crie uma senha segura",
    "auth.signIn": "Entrar",
    "auth.signingIn": "Entrando...",
    "auth.signupSubtitle": "Use um email válido e uma senha com pelo menos 6 caracteres.",
    "auth.signupTitle": "Criar conta",
    "search.title": "Buscar produtos",
    "search.subtitle": "Encontre instrumentos e álbuns por nome, categoria, descrição ou faixa de preço.",
    "search.firestoreFallback": "Usando produtos locais enquanto o Firestore é configurado.",
    "search.product": "Produto",
    "search.placeholder": "Exemplo: guitarra, vinil, 799",
    "search.inputHint": "Digite parte do nome, categoria, descrição ou preço do produto.",
    "search.inputLabel": "Buscar produto",
    "search.clearTextHint": "Limpa o texto pesquisado.",
    "search.clearTextLabel": "Limpar texto da busca",
    "search.categoryFilters": "Filtros de categoria",
    "search.all": "Todos",
    "search.noResults": "Nenhum produto encontrado",
    "search.noResultsText": "Tente buscar por guitarra, vinil, edição especial ou pelo preço.",
    "search.clearFilters": "Limpar filtros",
    "search.clearFiltersHint": "Remove o texto pesquisado e o filtro de categoria.",
    "search.showing": "Mostrando",
    "search.availableProducts": "produtos disponíveis",
    "search.foundSingular": "produto encontrado",
    "search.foundPlural": "produtos encontrados",
    "cart.title": "Carrinho",
    "cart.subtitle": "Revise os itens antes de seguir para o pagamento.",
    "cart.emptyTitle": "Carrinho vazio",
    "cart.emptyText": "Explore a loja e adicione seus instrumentos ou álbuns favoritos.",
    "cart.viewProductsHint": "Volta para a lista de produtos.",
    "cart.removeHint": "Remove este produto do carrinho.",
    "cart.summaryHint": "Próximo passo: pagamento seguro.",
    "cart.checkout": "Finalizar compra",
    "cart.checkoutHintLogged": "Abre a tela de pagamento.",
    "cart.checkoutHintGuest": "Abre a tela de login antes do pagamento.",
    "product.notFound": "Produto não encontrado",
    "product.backHint": "Retorna para a tela anterior.",
    "product.addToCart": "Adicionar ao carrinho",
    "product.addToCartHint": "Adiciona o produto ao carrinho e abre o carrinho.",
    "language.current": "PT",
    "tabs.cart": "Carrinho",
    "tabs.home": "Início",
    "tabs.profile": "Perfil",
    "tabs.search": "Busca",
    "home.dark": "Escuro",
    "home.featured": "Destaques da loja",
    "home.installments": "10x sem juros no cartão",
    "home.light": "Claro",
    "home.localProducts": "Usando produtos locais enquanto o Firestore é configurado.",
    "home.openProduct": "Abre a tela de detalhes do produto.",
    "home.subtitle":
      "Instrumentos, vinis e acessórios selecionados para quem vive música todos os dias.",
    "home.themeDark": "Ativar tema escuro",
    "home.themeLight": "Ativar tema claro",
    "home.themeToggleHint": "Alterna entre o tema claro e o tema escuro.",
    "home.title": "BlackTone Music",
    "home.type": "Loja Musical",
    "home.featuredList": "Lista de produtos em destaque",
    "profile.account": "Conta",
    "profile.addPhoto": "Adicionar foto de perfil",
    "profile.addPhotoHint": "Solicita permissão e abre a câmera para tirar uma foto de perfil.",
    "profile.cardMissing": "Cartão padrão ainda não cadastrado.",
    "profile.complete": "Completo",
    "profile.completeData": "Complete seus dados",
    "profile.completeDataText":
      "Salve CPF, endereço e cartão padrão para agilizar suas compras.",
    "profile.data": "Dados do usuário",
    "profile.dataDescription": "Adicione nome, CPF, nascimento e telefone.",
    "profile.history": "Histórico de compras",
    "profile.loginHint": "Abre a tela de login.",
    "profile.signup": "Cadastro",
    "profile.signupHint": "Abre a tela de cadastro.",
    "profile.loginText":
      "Entre ou crie uma conta para salvar histórico de compras e personalizar seu perfil.",
    "profile.logout": "Sair",
    "profile.logoutHint": "Sai da conta atual.",
    "profile.noAddress": "Endereço padrão ainda não cadastrado.",
    "profile.noPurchases": "Nenhuma compra ainda",
    "profile.noPurchasesText":
      "Quando você finalizar uma compra, os produtos aparecem aqui.",
    "profile.pending": "Pendente",
    "profile.title": "Perfil",
    "profile.profilePhoto": "Foto de perfil do usuário",
    "profile.noPhoto": "Perfil sem foto",
    "profile.cameraPermissionError": "Permissão da câmera negada. Verifique as configurações do aparelho.",
    "profile.ordersLoadError": "Não foi possível carregar o histórico do Firebase. Confira as regras do Firestore.",
    "profile.orderUpdateError": "Não foi possível atualizar o pedido no Firebase.",
    "profile.orderDeleteError": "Não foi possível excluir o pedido no Firebase.",
    "profile.purchaseDateMissing": "Data da compra indisponível",
    "profile.purchasedOn": "Comprado em",
    "profile.order": "Pedido",
    "profile.payment": "Pagamento",
    "profile.installmentIn": "em",
    "profile.openPurchasedProductHint": "Abre a página de detalhes deste produto comprado.",
    "profile.markDelivered": "Marcar entregue",
    "profile.orderDelivered": "Pedido entregue",
    "profile.markDeliveredHint": "Atualiza o status do pedido no Firebase para entregue.",
    "profile.deleteHistory": "Excluir histórico",
    "profile.deleteHistoryHint": "Exclui este pedido do histórico no Firebase.",
    "profile.statusCanceled": "Cancelado",
    "profile.statusDelivered": "Entregue",
    "profile.statusCreated": "Realizado",
    "profile.takePhoto": "Tirar foto",
    "profile.takePhotoHint": "Tira a foto de perfil.",
    "profile.switchCamera": "Trocar câmera",
    "profile.switchCameraHint": "Alterna entre câmera frontal e traseira.",
    "profile.cancelPhoto": "Cancelar foto",
    "profile.cancelPhotoHint": "Fecha a câmera sem salvar uma foto.",
    "account.address": "Endereço padrão",
    "account.addressHint":
      "Ele será carregado no checkout, mas ainda poderá ser alterado na hora de pagar.",
    "account.card": "Cartão padrão",
    "account.cardHint":
      "Para segurança, o app salva só dados de identificação do cartão. Número completo e CVV não ficam no Firebase.",
    "account.city": "Cidade",
    "account.complement": "Complemento",
    "account.cpf": "CPF",
    "account.fullName": "Nome completo",
    "account.header": "Dados do usuário",
    "account.myAccount": "Minha conta",
    "account.neighborhood": "Bairro",
    "account.number": "Número",
    "account.personal": "Informações pessoais",
    "account.personalHint":
      "Nome, CPF e nascimento ficam fora do checkout para manter a compra mais limpa.",
    "account.phone": "Telefone",
    "account.save": "Salvar dados da conta",
    "account.saved": "Dados salvos no Firebase.",
    "account.state": "UF",
    "account.street": "Rua",
    "account.subtitle":
      "Essas informações ficam no seu documento de usuário no Firestore.",
    "account.birthDate": "Nascimento",
    "account.loginRequiredTitle": "Entrar na conta",
    "account.loginRequiredText": "Entre para editar seus dados pessoais.",
    "account.backHint": "Volta para o perfil.",
    "account.saveHint": "Salva dados pessoais, endereço e cartão padrão no Firebase.",
    "account.namePlaceholder": "Seu nome",
    "account.birthDateLabel": "Data de nascimento",
    "account.streetPlaceholder": "Rua ou avenida",
    "account.numberPlaceholder": "123",
    "account.neighborhoodPlaceholder": "Bairro",
    "account.cityPlaceholder": "Cidade",
    "account.complementPlaceholder": "Apartamento, bloco, referência",
    "account.cardNickname": "Apelido",
    "account.cardNicknameLabel": "Apelido do cartão",
    "account.cardNicknamePlaceholder": "Cartão principal",
    "account.cardholder": "Nome impresso no cartão",
    "account.cardholderPlaceholder": "NOME SOBRENOME",
    "account.cardBrand": "Bandeira",
    "account.cardBrandLabel": "Bandeira do cartão",
    "account.cardBrandPlaceholder": "Visa",
    "account.cardLastFour": "Últimos 4",
    "account.cardLastFourLabel": "Últimos quatro dígitos do cartão",
    "account.cardExpiration": "Validade",
    "account.cardExpirationLabel": "Validade do cartão",
    "account.cardDefaultName": "Cartão principal",
    "account.cardDefaultBrand": "Cartão",
    "account.nameError": "Informe um nome com pelo menos 3 caracteres.",
    "account.cpfError": "Informe um CPF válido no formato 000.000.000-00.",
    "account.birthDateError": "Informe a data de nascimento no formato DD/MM/AAAA.",
    "account.cardLastFourError": "Para salvar o cartão, informe exatamente os últimos 4 dígitos.",
    "account.cardExpirationError": "Informe a validade do cartão no formato MM/AA.",
    "account.loginAgainError": "Entre novamente na conta para salvar seus dados no Firebase.",
    "account.saveError": "Não foi possível salvar os dados no Firebase. Tente novamente.",
    "cep.error": "Não foi possível buscar esse CEP. Confira os números ou preencha manualmente.",
    "cep.found": "Endereço encontrado pelo ViaCEP.",
    "cep.loading": "Buscando endereço pelo CEP...",
    "checkout.delivery": "Entrega",
    "checkout.summary": "Resumo",
    "checkout.paymentStep": "Pagamento",
    "checkout.productsSelected": "Produtos selecionados",
    "checkout.emptyCart": "Seu carrinho está vazio.",
    "checkout.emptyCartBackHint": "Volta para a loja.",
    "checkout.cpfRequired": "CPF obrigatório",
    "checkout.cpfRequiredText": "Cadastre seu CPF em Dados do usuário para finalizar compras.",
    "checkout.editProfileHint": "Abre a tela de dados do usuário.",
    "checkout.deliveryHint":
      "Usamos seu endereço padrão, mas você pode ajustar a entrega deste pedido.",
    "checkout.deliveryCepLabel": "CEP da entrega",
    "checkout.deliveryStateLabel": "Estado",
    "checkout.deliveryStreetLabel": "Rua",
    "checkout.deliveryNumberLabel": "Número do endereço",
    "checkout.deliveryNeighborhoodLabel": "Bairro",
    "checkout.deliveryCityLabel": "Cidade",
    "checkout.deliveryComplementLabel": "Complemento do endereço",
    "checkout.payment": "Forma de pagamento",
    "checkout.paymentHint": "Escolha uma forma de pagamento para liberar a revisão final.",
    "checkout.credit": "Crédito",
    "checkout.creditDetail": "Até 10x sem juros",
    "checkout.debit": "Débito",
    "checkout.debitDetail": "Débito online",
    "checkout.pix": "Pix",
    "checkout.pixDetail": "Aprovação rápida",
    "checkout.useDefaultCard": "Usar cartão padrão",
    "checkout.useDefaultCardHint": "Usa o cartão padrão salvo no perfil.",
    "checkout.useDefaultCardText": "Compra rápida com o cartão salvo no perfil.",
    "checkout.useAnotherCard": "Usar outro cartão",
    "checkout.useAnotherCardHint": "Permite digitar outro cartão somente para esta compra.",
    "checkout.useAnotherCardText": "Digite os dados do cartão desta compra.",
    "checkout.typeAtPurchase": "Digitar na compra",
    "checkout.cardFinal": "final",
    "checkout.cardNumber": "Número do cartão",
    "checkout.cardNumberHint": "Digite os 16 números do cartão.",
    "checkout.cardTestHint": "Para simular: 4242 4242 4242 4242, CVV 123 e validade futura.",
    "checkout.cvvHint": "Digite três ou quatro números do código de segurança.",
    "checkout.cardValidityHint": "Digite mês e ano da validade no formato mês barra ano.",
    "checkout.installments": "Parcelas",
    "checkout.review": "Revisar pedido",
    "checkout.reviewHint": "Valida os dados e abre a revisão do pedido antes de concluir.",
    "checkout.finalizing": "Finalizando pedido...",
    "checkout.finalTotal": "Total a pagar",
    "checkout.secure": "Seguro",
    "checkout.subtitle": "Revise os produtos, informe a entrega e escolha como pagar.",
    "checkout.title": "Finalizar compra",
    "checkout.total": "Total do pedido",
    "checkout.reviewModalLabel": "Revisar e confirmar pedido",
    "checkout.reviewTitle": "Revisar pedido",
    "checkout.reviewText": "Confira tudo antes de concluir a compra.",
    "checkout.items": "Itens",
    "checkout.method": "Forma",
    "checkout.backAndEdit": "Voltar e editar",
    "checkout.backAndEditHint": "Volta ao formulário de pagamento para corrigir os dados.",
    "checkout.confirmOrder": "Confirmar pedido",
    "checkout.confirmOrderHint": "Conclui a compra com os dados revisados.",
    "checkout.successTitle": "Compra realizada com sucesso!",
    "checkout.successText": "Seu pedido foi salvo no histórico de compras.",
    "checkout.goHome": "Ir para Home",
    "checkout.goHomeHint": "Fecha o aviso e volta para a página inicial.",
    "checkout.goHistory": "Ir para histórico",
    "checkout.goHistoryHint": "Fecha o aviso e abre o histórico de compras.",
    "checkout.removeProductHint": "Remove este produto do pedido.",
    "checkout.cartEmptyError": "Seu carrinho está vazio.",
    "checkout.cpfError": "Cadastre um CPF válido em Dados do usuário antes de finalizar.",
    "checkout.addressError": "Preencha rua, número, bairro, cidade e UF da entrega.",
    "checkout.paymentError": "Selecione a forma de pagamento.",
    "checkout.defaultCardError": "Cadastre um cartão padrão ou use outro cartão.",
    "checkout.cardDataError": "Preencha os dados do cartão.",
    "checkout.cardIncompleteError": "Número do cartão incompleto.",
    "checkout.cardInvalidError": "Número do cartão inválido. Use um cartão de teste válido.",
    "checkout.cvvError": "CVV incompleto.",
    "checkout.validityIncompleteError": "Validade incompleta.",
    "checkout.validityError": "Validade do cartão inválida ou vencida.",
    "checkout.installmentsError": "Selecione as parcelas.",
    "checkout.firebaseError": "Não foi possível salvar o pedido no Firebase. Confira as regras do Firestore e tente novamente.",
  },
  en: {
    "a11y.languageToggle": "Change app language",
    "a11y.brandLogo": "BlackTone Music logo",
    "common.back": "Back",
    "common.edit": "Edit",
    "common.loading": "Loading",
    "common.login": "Login",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.goToLogin": "Go to login",
    "common.item": "item",
    "common.items": "items",
    "common.price": "Price",
    "common.products": "Products",
    "common.remove": "Remove",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.total": "Total",
    "common.tryAgain": "Try again.",
    "common.viewProducts": "View products",
    "auth.backHint": "Goes back to the previous screen.",
    "auth.emailHint": "Enter your email in the format example@example.com.",
    "auth.emailPlaceholder": "example@example.com",
    "auth.emailRequired": "Enter your email.",
    "auth.emailRequiredSignup": "Enter an email.",
    "auth.emailInvalid": "Enter an email in the format example@example.com.",
    "auth.goToSignupHint": "Opens the sign-up screen.",
    "auth.createAccount": "Create account",
    "auth.creatingAccount": "Creating account...",
    "auth.createAccountHint": "Creates your account with email and password in Firebase.",
    "auth.email": "Email",
    "auth.haveAccount": "I already have an account",
    "auth.loginHint": "Signs in with Firebase Authentication.",
    "auth.loginSubtitle": "Access your account to finish purchases and track your history.",
    "auth.loginTitle": "Sign in to BlackTone",
    "auth.password": "Password",
    "auth.passwordHint": "Enter your password.",
    "auth.passwordPlaceholder": "At least 6 characters",
    "auth.passwordRequired": "Enter your password.",
    "auth.passwordRequiredSignup": "Enter a password.",
    "auth.passwordWeak": "Password must have at least 6 characters.",
    "auth.passwordHelper": "At least 6 characters.",
    "auth.emailSignupHint": "Enter your email for sign-up.",
    "auth.emailSignupLabel": "Sign-up email",
    "auth.passwordSignupHint": "Enter a password with at least 6 characters.",
    "auth.passwordSignupLabel": "Sign-up password",
    "auth.createAccountAndProfileHint": "Creates your account and opens your profile.",
    "auth.signupPasswordPlaceholder": "Create a secure password",
    "auth.signIn": "Sign in",
    "auth.signingIn": "Signing in...",
    "auth.signupSubtitle": "Use a valid email and a password with at least 6 characters.",
    "auth.signupTitle": "Create account",
    "search.title": "Search products",
    "search.subtitle": "Find instruments and albums by name, category, description or price range.",
    "search.firestoreFallback": "Using local products while Firestore is being configured.",
    "search.product": "Product",
    "search.placeholder": "Example: guitar, vinyl, 799",
    "search.inputHint": "Type part of the product name, category, description or price.",
    "search.inputLabel": "Search product",
    "search.clearTextHint": "Clears the search text.",
    "search.clearTextLabel": "Clear search text",
    "search.categoryFilters": "Category filters",
    "search.all": "All",
    "search.noResults": "No products found",
    "search.noResultsText": "Try searching for guitar, vinyl, special edition or price.",
    "search.clearFilters": "Clear filters",
    "search.clearFiltersHint": "Removes the search text and category filter.",
    "search.showing": "Showing",
    "search.availableProducts": "available products",
    "search.foundSingular": "product found",
    "search.foundPlural": "products found",
    "cart.title": "Cart",
    "cart.subtitle": "Review the items before going to payment.",
    "cart.emptyTitle": "Empty cart",
    "cart.emptyText": "Explore the store and add your favorite instruments or albums.",
    "cart.viewProductsHint": "Goes back to the product list.",
    "cart.removeHint": "Removes this product from the cart.",
    "cart.summaryHint": "Next step: secure payment.",
    "cart.checkout": "Checkout",
    "cart.checkoutHintLogged": "Opens the payment screen.",
    "cart.checkoutHintGuest": "Opens login before payment.",
    "product.notFound": "Product not found",
    "product.backHint": "Returns to the previous screen.",
    "product.addToCart": "Add to cart",
    "product.addToCartHint": "Adds the product to the cart and opens the cart.",
    "language.current": "EN",
    "tabs.cart": "Cart",
    "tabs.home": "Home",
    "tabs.profile": "Profile",
    "tabs.search": "Search",
    "home.dark": "Dark",
    "home.featured": "Store highlights",
    "home.installments": "10 interest-free installments",
    "home.light": "Light",
    "home.localProducts": "Using local products while Firestore is being configured.",
    "home.openProduct": "Opens the product details screen.",
    "home.subtitle": "Instruments, vinyl records and accessories for people who live music every day.",
    "home.themeDark": "Enable dark theme",
    "home.themeLight": "Enable light theme",
    "home.themeToggleHint": "Switches between light and dark theme.",
    "home.title": "BlackTone Music",
    "home.type": "Music Store",
    "home.featuredList": "Featured product list",
    "profile.account": "Account",
    "profile.addPhoto": "Add profile photo",
    "profile.addPhotoHint": "Requests permission and opens the camera to take a profile photo.",
    "profile.cardMissing": "Default card has not been saved yet.",
    "profile.complete": "Complete",
    "profile.completeData": "Complete your details",
    "profile.completeDataText": "Save CPF, address and default card to speed up purchases.",
    "profile.data": "User details",
    "profile.dataDescription": "Add name, CPF, birth date and phone.",
    "profile.history": "Purchase history",
    "profile.loginHint": "Opens the login screen.",
    "profile.signup": "Sign up",
    "profile.signupHint": "Opens the sign-up screen.",
    "profile.loginText": "Sign in or create an account to save purchases and personalize your profile.",
    "profile.logout": "Sign out",
    "profile.logoutHint": "Signs out of the current account.",
    "profile.noAddress": "Default address has not been saved yet.",
    "profile.noPurchases": "No purchases yet",
    "profile.noPurchasesText": "After checkout, purchased products will appear here.",
    "profile.pending": "Pending",
    "profile.title": "Profile",
    "profile.profilePhoto": "User profile photo",
    "profile.noPhoto": "Profile without photo",
    "profile.cameraPermissionError": "Camera permission denied. Check your device settings.",
    "profile.ordersLoadError": "Could not load history from Firebase. Check Firestore rules.",
    "profile.orderUpdateError": "Could not update the order in Firebase.",
    "profile.orderDeleteError": "Could not delete the order in Firebase.",
    "profile.purchaseDateMissing": "Purchase date unavailable",
    "profile.purchasedOn": "Purchased on",
    "profile.order": "Order",
    "profile.payment": "Payment",
    "profile.installmentIn": "in",
    "profile.openPurchasedProductHint": "Opens the detail page for this purchased product.",
    "profile.markDelivered": "Mark delivered",
    "profile.orderDelivered": "Order delivered",
    "profile.markDeliveredHint": "Updates this order status in Firebase to delivered.",
    "profile.deleteHistory": "Delete history",
    "profile.deleteHistoryHint": "Deletes this order from the Firebase history.",
    "profile.statusCanceled": "Canceled",
    "profile.statusDelivered": "Delivered",
    "profile.statusCreated": "Created",
    "profile.takePhoto": "Take photo",
    "profile.takePhotoHint": "Takes the profile photo.",
    "profile.switchCamera": "Switch camera",
    "profile.switchCameraHint": "Switches between front and back camera.",
    "profile.cancelPhoto": "Cancel photo",
    "profile.cancelPhotoHint": "Closes the camera without saving a photo.",
    "account.address": "Default address",
    "account.addressHint": "It will load at checkout, but you can still change it before paying.",
    "account.card": "Default card",
    "account.cardHint":
      "For safety, the app only saves card identification data. Full number and CVV are not stored in Firebase.",
    "account.city": "City",
    "account.complement": "Complement",
    "account.cpf": "CPF",
    "account.fullName": "Full name",
    "account.header": "User details",
    "account.myAccount": "My account",
    "account.neighborhood": "Neighborhood",
    "account.number": "Number",
    "account.personal": "Personal information",
    "account.personalHint": "Name, CPF and birth date stay outside checkout to keep payment cleaner.",
    "account.phone": "Phone",
    "account.save": "Save account details",
    "account.saved": "Details saved to Firebase.",
    "account.state": "State",
    "account.street": "Street",
    "account.subtitle": "This information is stored in your user document on Firestore.",
    "account.birthDate": "Birth date",
    "account.loginRequiredTitle": "Sign in",
    "account.loginRequiredText": "Sign in to edit your personal details.",
    "account.backHint": "Goes back to profile.",
    "account.saveHint": "Saves personal details, address and default card to Firebase.",
    "account.namePlaceholder": "Your name",
    "account.birthDateLabel": "Birth date",
    "account.streetPlaceholder": "Street or avenue",
    "account.numberPlaceholder": "123",
    "account.neighborhoodPlaceholder": "Neighborhood",
    "account.cityPlaceholder": "City",
    "account.complementPlaceholder": "Apartment, block, reference",
    "account.cardNickname": "Nickname",
    "account.cardNicknameLabel": "Card nickname",
    "account.cardNicknamePlaceholder": "Main card",
    "account.cardholder": "Name printed on card",
    "account.cardholderPlaceholder": "FULL NAME",
    "account.cardBrand": "Brand",
    "account.cardBrandLabel": "Card brand",
    "account.cardBrandPlaceholder": "Visa",
    "account.cardLastFour": "Last 4",
    "account.cardLastFourLabel": "Last four card digits",
    "account.cardExpiration": "Expiration",
    "account.cardExpirationLabel": "Card expiration",
    "account.cardDefaultName": "Main card",
    "account.cardDefaultBrand": "Card",
    "account.nameError": "Enter a name with at least 3 characters.",
    "account.cpfError": "Enter a valid CPF in the format 000.000.000-00.",
    "account.birthDateError": "Enter the birth date in DD/MM/YYYY format.",
    "account.cardLastFourError": "To save the card, enter exactly the last 4 digits.",
    "account.cardExpirationError": "Enter the card expiration in MM/YY format.",
    "account.loginAgainError": "Sign in again to save your details to Firebase.",
    "account.saveError": "Could not save the details to Firebase. Try again.",
    "cep.error": "Could not find this ZIP code. Check the digits or fill the address manually.",
    "cep.found": "Address found by ViaCEP.",
    "cep.loading": "Looking up address by ZIP code...",
    "checkout.delivery": "Delivery",
    "checkout.summary": "Summary",
    "checkout.paymentStep": "Payment",
    "checkout.productsSelected": "Selected products",
    "checkout.emptyCart": "Your cart is empty.",
    "checkout.emptyCartBackHint": "Goes back to the store.",
    "checkout.cpfRequired": "CPF required",
    "checkout.cpfRequiredText": "Save your CPF in User details before finishing purchases.",
    "checkout.editProfileHint": "Opens the user details screen.",
    "checkout.deliveryHint": "We use your default address, but you can adjust delivery for this order.",
    "checkout.deliveryCepLabel": "Delivery ZIP code",
    "checkout.deliveryStateLabel": "State",
    "checkout.deliveryStreetLabel": "Street",
    "checkout.deliveryNumberLabel": "Address number",
    "checkout.deliveryNeighborhoodLabel": "Neighborhood",
    "checkout.deliveryCityLabel": "City",
    "checkout.deliveryComplementLabel": "Address complement",
    "checkout.payment": "Payment method",
    "checkout.paymentHint": "Choose a payment method to unlock final review.",
    "checkout.credit": "Credit",
    "checkout.creditDetail": "Up to 10 interest-free installments",
    "checkout.debit": "Debit",
    "checkout.debitDetail": "Online debit",
    "checkout.pix": "Pix",
    "checkout.pixDetail": "Fast approval",
    "checkout.useDefaultCard": "Use default card",
    "checkout.useDefaultCardHint": "Uses the default card saved in profile.",
    "checkout.useDefaultCardText": "Fast checkout with the saved profile card.",
    "checkout.useAnotherCard": "Use another card",
    "checkout.useAnotherCardHint": "Lets you type another card only for this purchase.",
    "checkout.useAnotherCardText": "Enter the card details for this purchase.",
    "checkout.typeAtPurchase": "Type at checkout",
    "checkout.cardFinal": "ending",
    "checkout.cardNumber": "Card number",
    "checkout.cardNumberHint": "Enter the 16 card numbers.",
    "checkout.cardTestHint": "For testing: 4242 4242 4242 4242, CVV 123 and a future expiration date.",
    "checkout.cvvHint": "Enter three or four security code numbers.",
    "checkout.cardValidityHint": "Enter month and year in month slash year format.",
    "checkout.installments": "Installments",
    "checkout.review": "Review order",
    "checkout.reviewHint": "Validates the details and opens order review before finishing.",
    "checkout.finalizing": "Finishing order...",
    "checkout.finalTotal": "Total to pay",
    "checkout.secure": "Secure",
    "checkout.subtitle": "Review products, enter delivery and choose how to pay.",
    "checkout.title": "Checkout",
    "checkout.total": "Order total",
    "checkout.reviewModalLabel": "Review and confirm order",
    "checkout.reviewTitle": "Review order",
    "checkout.reviewText": "Check everything before completing the purchase.",
    "checkout.items": "Items",
    "checkout.method": "Method",
    "checkout.backAndEdit": "Back and edit",
    "checkout.backAndEditHint": "Returns to the payment form to correct the details.",
    "checkout.confirmOrder": "Confirm order",
    "checkout.confirmOrderHint": "Completes the purchase with the reviewed details.",
    "checkout.successTitle": "Purchase completed successfully!",
    "checkout.successText": "Your order was saved in purchase history.",
    "checkout.goHome": "Go to Home",
    "checkout.goHomeHint": "Closes the message and returns to the home page.",
    "checkout.goHistory": "Go to history",
    "checkout.goHistoryHint": "Closes the message and opens purchase history.",
    "checkout.removeProductHint": "Removes this product from the order.",
    "checkout.cartEmptyError": "Your cart is empty.",
    "checkout.cpfError": "Save a valid CPF in User details before finishing.",
    "checkout.addressError": "Fill street, number, neighborhood, city and state for delivery.",
    "checkout.paymentError": "Choose the payment method.",
    "checkout.defaultCardError": "Save a default card or use another card.",
    "checkout.cardDataError": "Fill the card details.",
    "checkout.cardIncompleteError": "Card number is incomplete.",
    "checkout.cardInvalidError": "Invalid card number. Use a valid test card.",
    "checkout.cvvError": "CVV is incomplete.",
    "checkout.validityIncompleteError": "Expiration is incomplete.",
    "checkout.validityError": "Card expiration is invalid or expired.",
    "checkout.installmentsError": "Choose the installments.",
    "checkout.firebaseError": "Could not save the order to Firebase. Check Firestore rules and try again.",
  },
} as const;

type TranslationKey = keyof typeof translations.pt;

export const LanguageContext = createContext<LanguageContextType>(
  {} as LanguageContextType
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("pt");

  function toggleLanguage() {
    setLanguage((current) => (current === "pt" ? "en" : "pt"));
  }

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      toggleLanguage,
      t: (key: TranslationKey) => translations[language][key] ?? translations.pt[key],
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
